// GENERATED BY CLAUDE FOR TESTING

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Simple array manipulation function
int find_max(const int arr[], int size) {
    if (size <= 0) return -1;

    int max = arr[0];
    for (int i = 1; i < size; i++) {
        if (arr[i] > max) {
            max = arr[i];
        }
    }
    return max;
}

// String manipulation with dynamic memory
char* reverse_string(const char* input) {
    if (!input) return NULL;

    int len = strlen(input);
    char* result = (char*)malloc((len + 1) * sizeof(char));
    if (!result) return NULL;

    for (int i = 0; i < len; i++) {
        result[i] = input[len - 1 - i];
    }
    result[len] = '\0';
    return result;
}

// Struct example with pointer manipulation
typedef struct Node {
    int data;
    struct Node* next;
} Node;

Node* create_node(int value) {
    Node* new_node = (Node*)malloc(sizeof(Node));
    if (new_node) {
        new_node->data = value;
        new_node->next = NULL;
    }
    return new_node;
}

// Function with output parameters
void get_array_stats(const int arr[], int size, int* min, int* max, float* avg) {
    if (size <= 0 || !min || !max || !avg) return;

    *min = *max = arr[0];
    int sum = arr[0];

    for (int i = 1; i < size; i++) {
        if (arr[i] < *min) *min = arr[i];
        if (arr[i] > *max) *max = arr[i];
        sum += arr[i];
    }

    *avg = (float)sum / size;
}

// Variadic function example
void print_formatted_numbers(const char* format, int count, ...) {
    va_list args;
    va_start(args, count);

    for (int i = 0; i < count; i++) {
        int num = va_arg(args, int);
        printf(format, num);
    }

    va_end(args);
    printf("\n");
}

// Example usage
int main() {
    // Test find_max
    int numbers[] = {4, 2, 9, 1, 7};
    printf("Max number: %d\n", find_max(numbers, 5));

    // Test reverse_string
    char* reversed = reverse_string("Hello");
    if (reversed) {
        printf("Reversed: %s\n", reversed);
        free(reversed);
    }

    // Test get_array_stats
    int min, max;
    float avg;
    get_array_stats(numbers, 5, &min, &max, &avg);
    printf("Stats - Min: %d, Max: %d, Avg: %.2f\n", min, max, avg);

    // Test variadic function
    print_formatted_numbers("%d ", 3, 10, 20, 30);

    return 0;
}